### ISSUE TITLE
iced_layershell: continuously doing something despite nothing changing

### ISSUE THREAD

**Issue by WhySoBad** [waycrate/exwlshelleventloop#159]
Hi,

I'm experiencing a high CPU usage for my application using the `iced_layershell` crate of about 9% to 20%. I'm using the `iced14` branch and using the new `debug` feature flag I've attached `comet` to the application. I don't think it's an regression since I'm experiencing similar CPU usage on an old version of my application which uses `iced 0.13.1` but there I can't attach `comet`.

I've noticed that the application is constantly rendering (or doing something at least) since in `comet` the charts have constant new updates. When attaching `comet` to the `tour` example of the iced repository one can see that this application only does something if effectively something changes (e.g. cursor move, button press) and otherwise nothing happens.

**How to reproduce**:

iced tour example (as reference how it should be):

1. clone iced repository
2. run tour example
3. attach `comet` by pressing F12

iced layershell application launcher example (how it is with `iced_layershell`):

1. enable debug flag for `iced_layershell` dependency
2. run application launcher example
3. attach `comet` by pressing F12

I'd suspect that this constant action in `iced_layershell` is the cause for the high CPU usage

*I don't think this is the same as #78 as the other issue seems to be a problem in iced whilst this is a problem in this crate. However, the high CPU usage noticed in the other issue could originate from this problem*

**Comment by Decodetalkers** [comment]
Can you try latest commit? I think I have fixed it

**Comment by WhySoBad** [comment]
The issue persists independent of the feature flag being turned on or off

**Comment by Decodetalkers** [comment]
have you follow https://github.com/waycrate/exwlshelleventloop/pull/138/commits/491704681a01a660278bf069cf026a35a3eed79d this commit?

**Comment by WhySoBad** [comment]
yes, I'm on https://github.com/waycrate/exwlshelleventloop/commit/24c937e4c47ecc94fd46ef9cd86dbfe9c70a624f

**Comment by Decodetalkers** [comment]
> yes, I'm on [24c937e](https://github.com/waycrate/exwlshelleventloop/commit/24c937e4c47ecc94fd46ef9cd86dbfe9c70a624f)

Then I cannot know what happened.. I do not have that energy now. I have follow the change in iced, just update when state changed

**Comment by WhySoBad** [comment]
No problem, but I don't think it's an regression as the `master` branch of `iced_layershell` also has this high CPU usage.

**Comment by Decodetalkers** [comment]
by the way, what is comet

**Comment by WhySoBad** [comment]
it's the iced debugger you added with the `debug` flag https://github.com/iced-rs/comet

**Comment by Decodetalkers** [comment]
Fixed, please update the commit

**Comment by WhySoBad** [comment]
I've ran my application with a profiler and found that this timeout is the reason for the high CPU usage:
https://github.com/waycrate/exwlshelleventloop/blob/1e5c1710455f4922d5b1946948dae9379140867d/layershellev/src/lib.rs#L2490

When I changed the timeout from 1ms to 100ms the CPU usage went to 0% and everything still worked as expected

**Comment by Decodetalkers** [comment]
Then you can make a pr for me, I will accept it

**Comment by WhySoBad** [comment]
I've just found that when moving the cursor over the surface the CPU usage spikes to 50% whilst on the `tour` iced example it only spikes to 10%. Probably, there is some sampling timeout set very low somewhere?

I'll have a look later today, maybe I can find it

**Comment by Decodetalkers** [comment]
> I've just found that when moving the cursor over the surface the CPU usage spikes to 50% whilst on the `tour` iced example it only spikes to 10%. Probably, there is some sampling timeout set very low somewhere?
> 
> I'll have a look later today, maybe I can find it
> 
> **edit**: The `MouseMotion` event is the problem, it's fired too often when the cursor is moving above the surface. I think we should somehow debounce those events since at the moment we rerender on every event (I at least think so)

maybe you can read the code of winit, maybe some part we do not make it right, anyway, the dispatch should be solved

**Comment by WhySoBad** [comment]
I've had a look at the code and followed the events. As already said, we get a lot of `MouseMotion` events which cause a lot of `NormalDispatch` events to be handled in the callback function passed to the `running_with_proxy` function. This then causes a lot of `RequestSetCursorShape` and `RedrawAllRequest` events which are probably the reason for the high CPU usage. 

However, I don't fully understand what all of these events do and how the inner workings of this crate are. It would be nice if you could give it a look and maybe come up with a solution. 

In the meantime, I open a pull request which fixes the dispatch time

**Comment by WhySoBad** [comment]
So there is a problem with increasing the timeout duration there. Since this loop is the main event loop running on the main thread, increasing the duration will block the main thread for this given amount of time. 

For example, when I set the duration to `Duration::from_millis(1000)` and I have an iced `every(Duration::from_millis(100))` subscription, the loop would only execute once a second since the subscription event is not a wayland event and therefore not covered by the dispatch.

I'm not very familiar with the iced event loop and I don't know all places where events can occur but the event loop needs to be modified somehow such that it waits for the first `iced` event or the first wayland event and the executes the loop. Similar how the [tokio select! macro](https://docs.rs/tokio/latest/tokio/macro.select.html) works in an async context.

**Comment by Decodetalkers** [comment]
can you take a try at this pr? https://github.com/waycrate/exwlshelleventloop/pull/172

if it can fix that, I will do same thing to sessionlock

**Comment by WhySoBad** [comment]
I don't know the full extent of your changes but you're doing basically the same thing as before here now with a 2ms timeout instead of a 1ms timeout:

https://github.com/waycrate/exwlshelleventloop/blob/a23e978436394a6072020b7c4998a2c45b8bc022/layershellev/src/lib.rs#L2492

This still causes a high CPU usage since the loop is executed at least 500times/sec. As this is the main drawing loop, this loop should only be executed as often as we need to achieve the desired framerate (e.g. to achieve 60 fps we would need a timeout of 16.667ms). However, this is still kindof inefficient since this would mean that the loop would still be unnecessarily be run a lot. On my machine I experience up to 10% CPU usage per execution of the loop (this is pretty good visible in `btop` with a >100ms delay). This is bad because my UI is pretty static (only updating once a minute) but still uses that much CPU power.

Ideally, we would have two loops running in different threads:
- The draw loop which handles all the UI drawing etc. This loop should only be executed as often as needed (if nothing is being redrawn it should not do unnecessary cycles) 
- The wayland event loop which blockingly waits for new wayland events and sends draw signals through a channel to the draw loop

Do you know whether it's possible to have the main loop in an async context? Then it would be very convenient to use a tokio select! statement to implement the draw loop.

**Comment by Decodetalkers** [comment]
> I don't know the full extent of your changes but you're doing basically the same thing as before here now with a 2ms timeout instead of a 1ms timeout:
> 
> https://github.com/waycrate/exwlshelleventloop/blob/a23e978436394a6072020b7c4998a2c45b8bc022/layershellev/src/lib.rs#L2492
> 
> This still causes a high CPU usage since the loop is executed at least 500times/sec. As this is the main drawing loop, this loop should only be executed as often as we need to achieve the desired framerate (e.g. to achieve 60 fps we would need a timeout of 16.667ms). However, this is still kindof inefficient since this would mean that the loop would still be unnecessarily be run a lot. On my machine I experience up to 10% CPU usage per execution of the loop (this is pretty good visible in `btop` with a >100ms delay). This is bad because my UI is pretty static (only updating once a minute) but still uses that much CPU power.
> 
> Ideally, we would have two loops running in different threads:
> - The draw loop which handles all the UI drawing etc. This loop should only be executed as often as needed (if nothing is being redrawn it should not do unnecessary cycles) 
> - The wayland event loop which blockingly waits for new wayland events and sends draw signals through a channel to the draw loop
> 
> Do you know whether it's possible to have the main loop in an async context? Then it would be very convenient to use a tokio select! statement to implement the draw loop.

So is its performance up? Now just 10%.
And I think it is impossible to split it to two threads. And in this way, the above part seems to be involved when there are some events. I have read the calloop,  and try this way. Winit should be using same way to handle evenys

**Comment by Decodetalkers** [comment]
Ok, I have a good idea. I will modify the code later

**Comment by Decodetalkers** [comment]
after thinking about, I will keep the change as now it like, but change the duration to 50. These is no need to concern about that it rerender too much time, because the rerender only happens when there is new message tell it to render or invoke render outside. Now the pr make the dispatch outside, and set it to use 500ms to do dispatch. and the 2ms means the source will  will expire in 2 millis, not means it will refresh for 2 millis, if I do not misunstand the document

**Comment by WhySoBad** [comment]
I think this is a good compromise for now :)
